name: 'nightly artifacts cleanup'
on:
  schedule:
    - cron: '0 13 */7 * *'
  workflow_dispatch:

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.RELEASE_KEY }}
          expire-in: 0
