name: Go Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17'

      - name: Build
        run: |
          # 下载代码
          git clone https://github.com/cloverstd/tcping.git
          cd tcping

          # 下载编译脚本并编译所有支持的架构/系统对
          curl -LOJ https://github.com/gek64/build-apps-scripts/raw/main/gobuilder.sh
          bash gobuilder.sh --os linux --arch linux

          # 下载源代码
          curl -LOJ https://github.com/cloverstd/tcping/archive/refs/heads/master.zip

          rope_name=$(echo "${{ GITHUB_REPOSITORY }}" | awk '{split($0,temp_array,"/"); print temp_array[2]}')
          git clone https://github.com/${{ GITHUB_REPOSITORY }}.git
          rm -rf "$rope_name"/tcping/*
          mv bin/* "$rope_name"/tcping/
          cd "$rope_name"
          git push -f origin main

