name: tcping build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17'

      - name: Build
        run: |
          # 删除旧的文件
          rm -rf tcping/*

          # 临时路径
          mkdir -p "tmp"
          cd tmp || exit

          git clone https://github.com/gek64/gek.git
          git clone https://github.com/gek64/gobuilder.git
          git clone https://github.com/cloverstd/tcping.git
          
          cd gobuilder || exit
          go build -v -trimpath -ldflags "-s -w" -o "../gobuilder_runner"
          chmod +x "../gobuilder_runner"
          cd .. || exit

          cd tcping || exit
          mkdir bin
          "../gobuilder_runner" -main -d bin

          curl --create-dirs --output-dir bin -LOJ https://github.com/cloverstd/tcping/archive/refs/heads/master.zip
          mv "bin/*" "../tcping"

          cd .. || exit
          rm -rf tmp

          # push到现有仓库
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add -A
          git commit -m "$(date +"%Y%m%d")"
          git push origin "$GITHUB_REF"
